name: Memory Leak Tests

on:
  push:
  pull_request:

jobs:
  memcheck:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Install dependencies
        run: | 
          sudo apt update
          sudo apt install -y build-essential valgrind
          pip3 install numpy
          sudo bash .github/build_upmem_toolchain.sh

      - name: Extract training samples & labels
        run: python3 read_dataset.py

      - name: Compile MLP without sanitizer or UPMEM
        run: |
          source /usr/local/bin/upmem-2024.2.0-Linux-x86_64/upmem_env.sh simulator
          make SAN=0 UPMEM=0

      - name: Run Valgrind
        run: | 
          source /usr/local/bin/upmem-2024.2.0-Linux-x86_64/upmem_env.sh simulator
          valgrind --leak-check=full \
                   --show-leak-kinds=all \
                   --track-origins=yes \
                   --error-exitcode=1 \
                   --log-file=valgrind.txt \
                   ./build/mlp > /dev/null
      
      - name: Save Valgrind log
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: valgrind_log
          path: valgrind.txt

      - name: Compile MLP with sanitizer and UPMEM
        run: |
          source /usr/local/bin/upmem-2024.2.0-Linux-x86_64/upmem_env.sh simulator
          make clean
          make SAN=1 UPMEM=1

      - name: Run with sanitizer
        run: |
          source /usr/local/bin/upmem-2024.2.0-Linux-x86_64/upmem_env.sh simulator
          ./build/mlp > /dev/null