name: Unit Tests

on: 
  push:
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Install dependencies
        run: | 
          sudo apt update && sudo apt install -y build-essential
          sudo bash .github/build_upmem_toolchain.sh
          
      - name: Test Installation
        run: |
          source /usr/local/bin/upmem-2024.2.0-Linux-x86_64/upmem_env.sh
          which dpu-lldb

      - name: Create build directory
        run: |
          source /usr/local/bin/upmem-2024.2.0-Linux-x86_64/upmem_env.sh
          mkdir build
      
      - name: Run CMake
        working-directory: build
        run: |
          source /usr/local/bin/upmem-2024.2.0-Linux-x86_64/upmem_env.sh
          cmake ..

      - name: Build
        working-directory: build
        run: |
          source /usr/local/bin/upmem-2024.2.0-Linux-x86_64/upmem_env.sh
          make

      - name: Run the tests
        working-directory: build
        run: |
          source /usr/local/bin/upmem-2024.2.0-Linux-x86_64/upmem_env.sh
          make test