name: Valgrind

on:
  push:
  pull_request:

jobs:
  memcheck:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Install dependencies
        run: | 
          sudo apt update
          sudo apt install -y build-essential valgrind python3.10 python3.10-dev
          pip3 install numpy
          sudo bash .github/build_upmem_toolchain.sh

      - name: Extract training samples & labels
        run: python3 read_dataset.py

      - name: Compile MLP
        run: |
          source /usr/local/bin/upmem-2024.2.0-Linux-x86_64/upmem_env.sh
          make

      - name: Run Valgrind
        run: | 
          source /usr/local/bin/upmem-2024.2.0-Linux-x86_64/upmem_env.sh
          valgrind --leak-check=full \
                   --show-leak-kinds=all \
                   --track-origins=yes \
                   --error-exitcode=1 \
                   --log-file=valgrind.txt \
                   ./build/mlp > /dev/null
      
      - name: Save Valgrind log
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: valgrind_log
          path: valgrind.txt